name: Publish Python module to TestPyPI

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64
        CIBW_ENVIRONMENT_LINUX: CHOOSENIM_CHOOSE_VERSION="1.6.8" PATH="/root/.nimble/bin:$PATH"
        CIBW_BEFORE_ALL_LINUX: curl -O https://nim-lang.org/choosenim/init.sh && sh init.sh -y
        CIBW_BEFORE_BUILD: nimble install -y
      with:
        package-dir: .
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pip install build nython && python -m build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
