name: Publish Python module to TestPyPI

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_ENVIRONMENT_LINUX: CHOOSENIM_CHOOSE_VERSION="1.6.8"
        CIBW_BEFORE_ALL_LINUX: curl https://nim-lang.org/choosenim/init.sh -sSf | sh -y
      with:
        package-dir: .
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
